[package]
name = "pd-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
log = "0.4.22"
env_logger = "0.11.5"
either = "1.13.0"
itertools = "0.13.0"
rayon = "1.5"
uuid = { version = "1.1", features = ["v4"] }
